### ISSUE TITLE
If I want to use this in the frontend, what would be the best way to extract it into a function?

### ISSUE THREAD

**Issue by deemeetree** [graphology/graphology-communities-louvain#3]

**Comment by deemeetree** [comment]
Via broserify

**Comment by deemeetree** [comment]
Ok, I think it can be useful for others to know how they can do that exactly, so I'll reopen the issue and leave it here:

First, I install `graphology-communities-louvain` as per instructions.

Then I create a file `louvain.js` with the following content:

```
var louvain = require('./node_modules/graphology-communities-louvain');

window.louvain_process = function (input) {
  louvain.assign(input);
  // alternatively you can also add const communities = louvain(graph); and return that as well
  return input;
}

```

Then I run browserify:

`browserify louvain.js -o graphology-louvain.js`

Then I include the `graphology-louvain.js` file into my frontend via the `script` tag and the function is exposed via

`louvain_process()`

However, to make it work, I have to first include the 

`<script src="/javascripts/graphology.min.js"></script>`

From the main library 

Then activate the graph object in my script:

`const graph = new graphology.Graph();`

Then construct it using my own datastructure (if I'm not using graphology):

`graph.addNode(n.id);`

`graph.addEdge(edge_data[i].source, edge_data[i].target, {weight: edge_data[i].weight});`

Then I add the community information to the graph using:

`graph = louvain_process(graph);`

If I want to expose modularity, I have to create a `js` file from the graphology-metrics with a modularity function exposed as in issue #4 and pass that new `graph` object to that function.

**Comment by Yomguithereal** [comment]
> And yes, would be great to have the static build just in case somebody else needs it in the frontend.

A lot of people use npm and webpack/browserify etc. to package js code for frontend nowadays. But I agree with you. I just did not create static builds for each library because I am lazy :)

You should definitely check [graphology-library](https://github.com/graphology/graphology-library) which is basically an aggregation of all the libraries gravitating around graphology. If you use browserify on it you'll get nearly everything in the build (but shipped code will be heavier of course).

**Comment by deemeetree** [comment]
Thanks! At the moment, I just did this to get the graph constructor, the community detection and modularity. But the file is quite big. Maybe I did something wrong and I can make it more lean? I mean I'm loading the main module just to construct the `Graph` but maybe it's superfluous?

```
var graphology = require('./node_modules/graphology');
var louvain = require('./node_modules/graphology-communities-louvain');
var modularity = require('./node_modules/graphology-metrics/modularity.js');

window.graphology = function () {
  const graph = new Graph();
  return graph;
}
window.graphology_process = function (input) {
  louvain.assign(input);
  return input;
}
window.graphology_modularity = function (input) {
  const mod = modularity(input);
  return mod;
}

```

**Comment by Yomguithereal** [comment]
The issue here is that the graph implementation itself is quite hefty. It cannot be more lean without sacrificing a lot. But minified it should be quite light. One day I’ll also provide ways to run some of the metrics etc. on ligther structures such as basi adjacency matrices etc but I need to find time for that.
