### ISSUE TITLE
Is there a way to change the way nodes are mapped to communities?

### ISSUE THREAD

**Issue by deemeetree** [graphology/graphology-communities-louvain#5]
I was wondering why the nodes are mapped to community names that have the same name as nodes. What is the criteria and the logic behind it? I mean, I'm not against it or anything, but just curious the reason for choosing that.

And also — is there a way to change that mapping to something else, say, just code numbers for each community (etc. `0, 1, 2, 3`). 

Thanks and great work with graphology!

**Comment by Yomguithereal** [comment]
> I was wondering why the nodes are mapped to community names that have the same name as nodes. What is the criteria and the logic behind it? I mean, I'm not against it or anything, but just curious the reason for choosing that.

If I remember correctly it's just easier to implement this way because some nodes become their cluster's keys and you can avoid some hashmap lookups thanks to it.

This said, I am not opposed to adding an option returning a numeric key instead or even array of arrays or else. The core code of this library shall be rewritten soon to make it a little more snappy. (I also need to implement the [Leiden](https://arxiv.org/abs/1810.08473) method).

**Comment by Yomguithereal** [comment]
Hello @deemeetree. The algorithm now returns an integer range as communities.
